name: Append Gsheet
on:
  workflow_dispatch:
  
jobs:
  appendrow:
    runs-on: ubuntu-latest
    steps:
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.2.0
        with:
          spreadsheetId: "1XCI7IKwQSEvp2w_3zeB2D05X2evx_UGPG4hKaUT_zk0"
          commands: |
            [
              { "command": "addWorksheet", "args": { "worksheetTitle": "TestWorksheet" }}
            ]
    env:
      GSHEET_CLIENT_EMAIL: enfmailbot@eosn.foundation
      GSHEET_PRIVATE_KEY: ${{ secrets.ENFMAILBOT_PASSWORD }}
          
