name: Append Gsheet
on:
  workflow_dispatch:
  
jobs:
  appendrow:
    runs-on: ubuntu-latest
    steps:
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.2.0
        with:
          spreadsheetId: ${{ secrets.SPREADSHEET_ID }}  
          commands: |
            [
              { "command": "addWorksheet", "args": { "worksheetTitle": "FHorse" }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: enf-grant-bot@absolute-codex-350620.iam.gserviceaccount.com
          #GSHEET_CLIENT_EMAIL: 	enfmailbot@eosn.foundation
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_API_KEY }}
      - name: dump results
        env:
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS"
        
# { "command": "addWorksheet", "args": { "worksheetTitle": "TestWorksheet1", "spreadsheetId": "1XCI7IKwQSEvp2w_3zeB2D05X2evx_UGPG4hKaUT_zk0" }}
