name: Call a reusable parser

on:
  workflow_dispatch:

jobs:
  call-parser:
    uses: ./.github/workflows/reusable-parser.yml
    with:
      filename: "actions/oci-transaction-lifecycle.md"
    
  echo-the-returned-fields:
    runs-on: ubuntu-latest
    needs: call-parser
    steps:
      - run: echo "project name ${{ needs.call-parser.outputs.project_name }} app_email ${{ needs.call-parser.outputs.app_email }}"
