# This workflow will parse the grant application, get needed data, and then send an email to the grant submitter
#
# getFilename.yml
#
# For now I am just testing that I can retrieve the file name on the pull request

name: getFileName

# Controls when the workflow will run
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
  
          #env:
        # ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  get_filename:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.files.outputs.added }}
    steps:
      - name: Get application file name
        id: 'files'
        uses: Ana06/get-changed-files@v2.0.0
        with:
          filter: 'applications/*.md'

  parse_app:
    needs: get_filename
    if: needs.get_filename.outputs.filename
    runs-on: ubuntu-latest
    outputs:
      app_email: ${{ steps.grep_email.outputs.email_addr }}
      contact_name: ${{ steps.grep_email.outputs.contact_name }}
      project_name: ${{ steps.grep_email.outputs.project_name }}
      team_name: ${{ steps.grep_email.outputs.team_name }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Echo_file
        run: echo This is the file ${{ needs.get_filename.outputs.filename }}
        
      # Parse the application template for the email account
      - name: assign the env from the email name
        id: grep_email
        run: |
          export APP_EMAIL=`/bin/grep "**Contact Email:**" ${{ needs.get_filename.outputs.filename }} | cut -d" " -f4`
          #echo "::set-env name=APP_EMAIL::$APP_EMAIL"
          echo "::set-output name=email_addr::$APP_EMAIL"
          export CNAME=`/bin/grep "**Contact Name:**" ${{ needs.get_filename.outputs.filename }} | cut -d" " -f4-8`
          echo "::set-output name=contact_name::$CNAME"
          export PNAME=`/bin/grep "**Project Name:**" ${{ needs.get_filename.outputs.filename }} | cut -d" " -f4-8`
          echo "::set-output name=project_name::$PNAME"
          export TNAME=`/bin/grep "**Team Name:**" ${{ needs.get_filename.outputs.filename }} | cut -d" " -f4-8`
          echo "::set-output name=team_name::$TNAME"

      # Now echo the saved ENV name
      # - name: Echo the env email name inside the same job
      # run: echo "the env email name is ${APP_EMAIL} from the application - single step"
      
  send_email:
    needs: [get_filename, parse_app]
    runs-on: ubuntu-latest
    steps:

      # Now echo the saved output variable
      - name: Echo the output names across jobs
        run: |
          echo "the output email name is ${{needs.parse_app.outputs.app_email}} from the application"
          echo "the output contact name is ${{needs.parse_app.outputscontact_name}} from the application"
          echo "the output project name is ${{needs.parse_app.outputs.project_name}} from the application"
          echo "the output team name is ${{needs.parse_app.outputs.team_name}} from the application"
      
