name: Label Dispatcher
on:
  pull_request:
    types: labeled
  
jobs:
  get_filename:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.files.outputs.added }}
    steps:
      - name: Get grant application file name
        id: 'files'
        uses: Ana06/get-changed-files@v2.0.0
        with:
          filter: 'applications/*.md'
          
  checklabel:
    needs: get_filename
    runs-on: ubuntu-latest
    steps:
    - name: Grant Received
      id: send-the-email
      if: github.event.label.name == 'Grant Received'
      run: echo "Grant Received label was added to application file ${{ needs.get_filename.outputs.filename }}"
    
    - name: Grant Translated
      if: github.event.label.name == 'Grant Translated'
      id: add-to-spreadsheet
      run: echo "Grant Translated label was added to application file ${{ needs.get_filename.outputs.filename }}"

  alwaysrun:
    needs: checklabel
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: alwaysrunthis
      id: in-case-no-labels-matched
      run: echo "Always step was run to avoid error notice"
  
   
