name: Big Scrape

on:
  workflow_dispatch:
    inputs:
      AppFile:
        type: string
        description: Name of Application File
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: greet
        run: | 
          echo "Application file is: ${{ github.event.inputs.AppFile }}"
          export APP_EMAIL=`/bin/grep "**Contact Email:**" "applications/${{ github.event.inputs.AppFile }}" | cut -d" " -f4`
          echo "::set-output name=email_addr::$APP_EMAIL"
          echo email addr is $APP_EMAIL

  call-parser:
    uses: ./.github/workflows/ru-big-parser.yml
    with:
      filename: "applications/${{ github.event.inputs.AppFile }}"
    needs: build

  echo-the-returned-fields:
    runs-on: ubuntu-latest
    needs: call-parser
    steps:
      - id: echo-output
        run: |
          echo "project name ${{ needs.call-parser.outputs.project_name }} "
          echo "contact name ${{ needs.call-parser.outputs.contact_name }}"
          echo "team name ${{ needs.call-parser.outputs.team_name }}"
          echo "app_email ${{ needs.call-parser.outputs.app_email }}"
          echo "total cost ${{ needs.call-parser.outputs.total_cost }}"

